### ISSUE TITLE
task within autopilot will not start

### ISSUE THREAD

**Issue by lucasogit** [wehr-lab/autopilot#129]
I get an error when trying to start a task that used to work fine. The error is as follows:

`Traceback (most recent call last):
  File "/home/lab/git/autopilot/autopilot/core/gui.py", line 561, in toggle_start
    self.start_fn(True, self.pilot, current_subject)
  File "/home/lab/git/autopilot/autopilot/core/terminal.py", line 536, in toggle_start
    task = self.subjects[subject].prepare_run()
  File "/home/lab/git/autopilot/autopilot/core/subject.py", line 650, in prepare_run
    trial_table = h5f.get_node(group_name, 'trial_data')
  File "/home/lab/git/autopilot/venv/lib/python3.7/site-packages/tables/file.py", line 1642, in get_node
    node = self._get_node(nodepath)
  File "/home/lab/git/autopilot/venv/lib/python3.7/site-packages/tables/file.py", line 1590, in _get_node
    node = self._node_manager.get_node(nodepath)
  File "/home/lab/git/autopilot/venv/lib/python3.7/site-packages/tables/file.py", line 432, in get_node
    node = self.node_factory(key)
  File "/home/lab/git/autopilot/venv/lib/python3.7/site-packages/tables/group.py", line 1178, in _g_load_child
    node_type = self._g_check_has_child(childname)
  File "/home/lab/git/autopilot/venv/lib/python3.7/site-packages/tables/group.py", line 395, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``/data/gap_laser_PV/S00_Free Water/trial_data``
`

**Comment by sneakers-the-rat** [comment]
This was due to an uncaught exception in finding the task class when assigning a subject, which is now handled <3
