### ISSUE TITLE
Run 2afc task error

### ISSUE THREAD

**Issue by pangpangshui** [wehr-lab/autopilot#54]
```
DEBUG:node._test_agent_2:RECEIVED: ID: test_agent_2_2; TO: _test_agent_2; SENDER: test_agent_2; KEY: START; FLAGS: {}; VALUE: {'bias_mode': 0, 'correction': False, 'graduation': {'type': 'n_trials', 'value': {'current_trial': '100', 'n_trials': '100', 'type': 'n_trials'}}, 'punish_dur': 100, 'punish_stim': True, 'req_reward': True, 'reward': 1000, 'step_name': '2AFC', 'stim': {'sounds': {}, 'tag': 'Sounds', 'type': 'sounds'}, 'task_type': '2AFC', 'subject': '111', 'step': 0, 'current_trial': 0, 'session': 12, 'pilot': 'test_agent_2'}
ERROR:task.<class 'autopilot.tasks.nafc.Nafc'>:Pin could not be instantiated - Type: POKES, Pin: L
Traceback (most recent call last):
  File "/home/pi/github/autopilot/autopilot/tasks/task.py", line 142, in init_hardware
    hw_args = pin_numbers[type][pin]
KeyError: 'POKES'
ERROR:task.<class 'autopilot.tasks.nafc.Nafc'>:Pin could not be instantiated - Type: POKES, Pin: C
Traceback (most recent call last):
  File "/home/pi/github/autopilot/autopilot/tasks/task.py", line 142, in init_hardware
    hw_args = pin_numbers[type][pin]
KeyError: 'POKES'
ERROR:task.<class 'autopilot.tasks.nafc.Nafc'>:Pin could not be instantiated - Type: POKES, Pin: R
Traceback (most recent call last):
  File "/home/pi/github/autopilot/autopilot/tasks/task.py", line 142, in init_hardware
    hw_args = pin_numbers[type][pin]
KeyError: 'POKES'
ERROR:task.<class 'autopilot.tasks.nafc.Nafc'>:Pin could not be instantiated - Type: LEDS, Pin: L
Traceback (most recent call last):
  File "/home/pi/github/autopilot/autopilot/tasks/task.py", line 142, in init_hardware
    hw_args = pin_numbers[type][pin]
KeyError: 'LEDS'
ERROR:task.<class 'autopilot.tasks.nafc.Nafc'>:Pin could not be instantiated - Type: LEDS, Pin: C
Traceback (most recent call last):
  File "/home/pi/github/autopilot/autopilot/tasks/task.py", line 142, in init_hardware
    hw_args = pin_numbers[type][pin]
KeyError: 'LEDS'
ERROR:task.<class 'autopilot.tasks.nafc.Nafc'>:Pin could not be instantiated - Type: LEDS, Pin: R
Traceback (most recent call last):
  File "/home/pi/github/autopilot/autopilot/tasks/task.py", line 142, in init_hardware
    hw_args = pin_numbers[type][pin]
KeyError: 'LEDS'
ERROR:task.<class 'autopilot.tasks.nafc.Nafc'>:Pin could not be instantiated - Type: LEDS, Pin: TOP
Traceback (most recent call last):
  File "/home/pi/github/autopilot/autopilot/tasks/task.py", line 142, in init_hardware
    hw_args = pin_numbers[type][pin]
KeyError: 'LEDS'
ERROR:task.<class 'autopilot.tasks.nafc.Nafc'>:Pin could not be instantiated - Type: PORTS, Pin: L
Traceback (most recent call last):
  File "/home/pi/github/autopilot/autopilot/tasks/task.py", line 142, in init_hardware
    hw_args = pin_numbers[type][pin]
KeyError: 'PORTS'
ERROR:task.<class 'autopilot.tasks.nafc.Nafc'>:Pin could not be instantiated - Type: PORTS, Pin: C
Traceback (most recent call last):
  File "/home/pi/github/autopilot/autopilot/tasks/task.py", line 142, in init_hardware
    hw_args = pin_numbers[type][pin]
KeyError: 'PORTS'
ERROR:task.<class 'autopilot.tasks.nafc.Nafc'>:Pin could not be instantiated - Type: PORTS, Pin: R
Traceback (most recent call last):
  File "/home/pi/github/autopilot/autopilot/tasks/task.py", line 142, in init_hardware
    hw_args = pin_numbers[type][pin]
KeyError: 'PORTS'
DEBUG:task.<class 'autopilot.tasks.nafc.Nafc'>:Hardware initialized
DEBUG:task.<class 'autopilot.tasks.nafc.Nafc'>:Stimulus manager initialized
DEBUG:main:Starting task loop
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/github/autopilot/autopilot/core/pilot.py", line 706, in run_task
    data = next(self.task.stages)() # Double parens because next just gives us the function, we still have to call it
  File "/home/pi/github/autopilot/autopilot/tasks/nafc.py", line 276, in request
    self.target, self.distractor, self.stim = self.stim_manager.next_stim()
  File "/home/pi/github/autopilot/autopilot/stim/managers.py", line 218, in next_stim
    self.last_stim = np.random.choice(self.stimuli[self.target])
KeyError: 'R'
```

I find this error is in here: task.py:init_hardware: hw_args = pin_numbers[type][pin]

I print `pin_numbers` is like:
```
{
	'GPIO': {
		'test': {
			'name': 'test',
			'pin': 21,
			'pins': '',
			'polarity': 1,
			'pull': 1,
			'pulse_width': 100,
			'trigger': '',
			'type': 'gpio.LED_SINGLE',
			'value': 1
		}
	}
}
```

and `self.HARDWARE` is like:
```
{
	'POKES': {
		'L': < class 'autopilot.hardware.gpio.Digital_In' > ,
		'C': < class 'autopilot.hardware.gpio.Digital_In' > ,
		'R': < class 'autopilot.hardware.gpio.Digital_In' >
	},
	'LEDS': {
		'L': < class 'autopilot.hardware.gpio.LED_SINGLE' > ,
		'C': < class 'autopilot.hardware.gpio.LED_SINGLE' > ,
		'R': < class 'autopilot.hardware.gpio.LED_SINGLE' > ,
		'TOP': < class 'autopilot.hardware.gpio.Digital_Out' >
	},
	'PORTS': {
		'L': < class 'autopilot.hardware.gpio.Solenoid' > ,
		'C': < class 'autopilot.hardware.gpio.Solenoid' > ,
		'R': < class 'autopilot.hardware.gpio.Solenoid' >
	}
}
```

dictionary `self.HARDWARE ` 's key has not been included in `pin_numbers`.  Did I have ignore somthing? Please help and thank. @sneakers-the-rat

**Comment by sneakers-the-rat** [comment]
I see two things here:

first, the `HARDWARE` parameterization in `prefs.json` needs to match the structure of the `HARDWARE` dictionary. (note that `pin_numbers` is just the `HARDWARE` parameterization from `prefs.json`: https://github.com/wehr-lab/autopilot/blob/f1a095e531b36a5a2fd8e8c6565bb664f4f821db/autopilot/tasks/task.py#L128 )

Please see 
* the docs for prefs: https://docs.auto-pi-lot.com/en/latest/autopilot.prefs.html
* this post on the discussion board that describes the rationale: https://groups.google.com/g/autopilot-users/c/_MqzLDDq3CE/m/KJYgHzkdAAAJ

Enough people are having trouble with this that I think it needs to be improved, but i'm not sure exactly what would be a better system yet. 

The second thing I see is 
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/github/autopilot/autopilot/core/pilot.py", line 706, in run_task
    data = next(self.task.stages)() # Double parens because next just gives us the function, we still have to call it
  File "/home/pi/github/autopilot/autopilot/tasks/nafc.py", line 276, in request
    self.target, self.distractor, self.stim = self.stim_manager.next_stim()
  File "/home/pi/github/autopilot/autopilot/stim/managers.py", line 218, in next_stim
    self.last_stim = np.random.choice(self.stimuli[self.target])
KeyError: 'R'
```

where it looks like there is a problem with the stimulus paramterization -- stimulus managers are the last remaining major piece of infrastructure left to be built, so their instantiation is relatively primitive at this point, but essentially the task needs to have `'L'`eft and `'R'`ight stimuli, see the the `stim` parameter in the docs for the task class ( https://docs.auto-pi-lot.com/en/latest/autopilot.tasks.nafc.html ):

which for the case of sound stimuli would look like this:
```
"sounds": {
    "L": [{"type": "Tone", ...}],
    "R": [{"type": "Tone", ...}]
}
```

currently other types of stimuli aren't implemented, but if you would like to present something else i would be happy to talk about what you need :)

let me know if you have further questions :)
